FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your app code
COPY clob_display.py .

ENV REDIS_HOST=redis
ENV REDIS_PORT=6379

CMD ["uvicorn", "clob_display:app", "--host", "0.0.0.0", "--port", "8002"]
